### ISSUE TITLE
Some kind of demo is needed

### ISSUE THREAD

**Issue by zoulja** [alesbrelih/gitlab-ci-ls#41]
This project looks like a life saver for me, but I found that almost no of declared features work in my case (I have very complicated CI with a lot of includes/references)
Only "Go to definition" in the same file works so far
Perhaps I'm doing something wrong or have high expectations
Do you mind to extend documentation with some animations/videos?
Thanks

**Comment by alesbrelih** [comment]
Hey, I'm glad you like the idea.

I'm testing this on not that simple of a project and it works.

There is one thing that comes to my mind when you described the issue. Are you using VS Code? Because one of the previous extensions had a bug. When you set the `.cache` path it needs to end with trailing slash else it bugs out.
And in one of previous iterations of VS Code extension it defaulted to `~/.cache/gitlab-ci-ls` instead of `~/.cache/gitlab-ci-ls/`. I need to fix this in language server itself (#soon).

I'll also upload a demo of functionalities.

**Comment by alesbrelih** [comment]
Hey I've just uploaded a video that showcases some of the functionalities. Link (can also be found on readme): https://vimeo.com/966578794
